### ISSUE TITLE
StockTrader RI with Unity ?

### ISSUE THREAD

**Issue by mjeson** [PrismLibrary/Prism-Samples-Wpf#12]
Is there a working sample of StockTrader RI with Unity instead of MEF ?

If not, I would like to contribute this work. 
https://github.com/mjeson/PrismSample-StockTraderRI-Unity

Most of the functionalities compile and run, but the Pie Chart and News popup do not show up yet. Hope to get help from this Prism community to have them working.

**Comment by brianlagunas** [comment]
Actually, I'm not a fan of the Stock Trader RI.  The implementation needs a complete rewrite.  The only reason we brought it over was because we needed samples sooner rather than later.

As soon as  get time, I will be creating a brand new RI sample that will help clear up some confusion around some concepts.  It will be written with Unity :).

**Comment by mjeson** [comment]
Yeah, I am not a fan either. Many of its classes are unnecessarily placed in the Infrastructure project although their usage is isolated specific to one module. It is definitely can be organized better.

Are you going to publish it soon ? Is there an opportunity to contribute ?

**Comment by brianlagunas** [comment]
I haven't even started.  Heck, I don't even have an idea of what the next RI app would be (an Outlook style app maybe).  I have been working on feature work and docs.  I haven't had time for samples.  We are always looking for contributions.  Keep in mind any samples will be reviewed since they represent the guidance on "best-practice".
