### ISSUE TITLE
I want to provide a sample about dialog service

### ISSUE THREAD

**Issue by Bdl-1989** [PrismLibrary/Prism-Samples-Wpf#84]
Hi all,

There is an introduction about dialog service on the PrismLibrary but no sample here.
I want to provide a dialog sample. How can I do that? Which number should I name for the folder?

Thanks.

**Comment by brianlagunas** [comment]
You should probably create three; one for just using the dialog, one for styling the dialog, and another for using a custom window. So that could number 26, 27, and 28.

Also be sure to follow the naming conventions that have been established by the other samples.  Keep the sample focused solely on just using the Dialog and nothing else.

**Comment by niimima** [comment]
I will challenge to create sample for just using the dialog.
I will refer to the following URL to proceed.
https://prismlibrary.com/docs/wpf/dialog-service.html

**Comment by brianlagunas** [comment]
@niimima that's great! Just be sure to follow the suggestions in my previous comment.

**Comment by niimima** [comment]
@brianlagunas 
I created pull request of [Create sample for using DialogService](https://github.com/PrismLibrary/Prism-Samples-Wpf/pull/92).
I will make three samples below.
26. using the dialog
27. styling the dialog
28. using a custom window
Now, I make "26. using the dialog" sample in pull request.

I understand that you are very busy but I would like to make two samples after accepted it, in case there are any mistakes.
Should I need to do anything for review?

**Comment by brianlagunas** [comment]
Sorry for the late response. I have been very busy. Thank you for your PR. It has been merged.
